version: '3'
services:
  eurekaserver:
     image:   coopersoft/cloud-eurekasvr:latest
     ports:
         - "8761:8761"
  configserver:
      image: coopersoft/cloud-confsvr:latest
      ports:
         - "8888:8888"
      environment:
         EUREKASERVER_PORT: 8761
         EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
         ENCRYPT_KEY:       "IMSYMMETRIC"
      links:
        - eurekaserver:discovery
  zuulserver:
      image: coopersoft/cloud-zuulsvr:latest
      ports:
        - "5555:5555"
      environment:
        PROFILE: "default"
        SERVER_PORT: "5555"
        CONFIGSERVER_PORT: 8888
        EUREKASERVER_PORT: 8761
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      links:
        - eurekaserver:discovery
  database:
      image: coopersoft/mariadb-min:v1
#      restart: always
#      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
      ports:
        - "3306:3306"
      volumes:
        - "/home/docker/data/db:/var/lib/mysql"
      environment:
        - MYSQL_ROOT_PASSWORD=p0stgr@s
        - MYSQL_DATABASE=archives
        TZ: Asia/Shanghai
#        - MYSQL_USER=testuser
#        - MYSQL_PASSWORD=testpassword


#        docker run --name mariadb_test -e MYSQL_ROOT_PASSWORD=my-secret=pw -d
#        docker run -d --name mariadb_volume -P -v /data/Db/mariadb:/var/lib/mysql mariadb

  mediaservice:
    image: coopersoft/seaweedfs-media-service:stable2
    ports:
      - "6699:6699"
    volumes:
      - "/home/docker/data/weedfs:/data"


  authenticationservice:
      image: coopersoft/cloud-authentication-service:latest
      ports:
        - "8901:8901"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8901"
        DATABASE_PORT:     3306
        CONFIGSERVER_PORT: 8888
        EUREKASERVER_PORT: 8761
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        ENCRYPT_KEY:       "IMSYMMETRIC"
      links:
          - eurekaserver:discovery
#  roomservice:
#      image: coopersoft/archive-room-service:archives
#      ports:
#        - "8085:8085"
#      environment:
#        PROFILE: "default"
#        SERVER_PORT: "8085"
#        DATABASE_PORT:     3306
#        CONFIGSERVER_PORT: 8888
#        EUREKASERVER_PORT: 8761
#        AUTHSERVER_PORT:   8091
#        CONFIGSERVER_URI: "http://configserver:8888"
#        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
#        AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
#        ENCRYPT_KEY:       "IMSYMMETRIC"
#      links:
#        - eurekaserver:discovery
#  businesstemplateservice:
#        image: coopersoft/business-template-service:archives
#        ports:
#          - "8086:8086"
#        environment:
#          PROFILE: "default"
#          SERVER_PORT: "8086"
#          DATABASE_PORT:     3306
#          CONFIGSERVER_PORT: 8888
#          EUREKASERVER_PORT: 8761
#          AUTHSERVER_PORT:   8091
#          CONFIGSERVER_URI: "http://configserver:8888"
#          EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
#          AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
#          ENCRYPT_KEY:       "IMSYMMETRIC"
#        links:
#          - eurekaserver:discovery
#  archivesbusinessservice:
#      image: coopersoft/archive-business-service:archives
#      ports:
#        - "8087:8087"
#      environment:
#        PROFILE: "default"
#        SERVER_PORT: "8087"
#        DATABASE_PORT:     3306
#        CONFIGSERVER_PORT: 8888
#        EUREKASERVER_PORT: 8761
#        AUTHSERVER_PORT:   8091
#        CONFIGSERVER_URI: "http://configserver:8888"
#        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
#        AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
#        ENCRYPT_KEY:       "IMSYMMETRIC"
#      links:
#        - eurekaserver:discovery
#  joincorpservice:
#      image: coopersoft/join-corp-service:archives
#      ports:
#        - "8089:8089"
#      environment:
#        PROFILE: "default"
#        SERVER_PORT: "8089"
#        DATABASE_PORT:     3306
#        CONFIGSERVER_PORT: 8888
#        EUREKASERVER_PORT: 8761
#        AUTHSERVER_PORT:   8091
#        CONFIGSERVER_URI: "http://configserver:8888"
#        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
#        AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
#        ENCRYPT_KEY:       "IMSYMMETRIC"
#      links:
#        - eurekaserver:discovery
#



