#开发环境被依赖下使用的参数, 本地开发测试时不使用此配置,请使用本的的 test 配置来改变依赖服务的地址

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    cc.coopersoft: DEBUG


spring:
  datasource:
    url: "jdbc:mysql://database:3306/CONSTRUCT?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false"
    username: "root"
    password: "{cipher}4788dfe1ccbe6485934aec2ffeddb06163ea3d616df5fd75be96aadd4df1da91"
    initialization-mode: always
  jpa:
    show-sql: "true"